DROP TABLE TBL_USER;
DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_USER;

CREATE TABLE TBL_USER(
	USER_ID NUMBER,
	LOGIN_ID VARCHAR2(1000),
	PASSWORD VARCHAR2(1000),
	NAME VARCHAR2(1000),
	GENDER CHAR(1),
	CONSTRAINTS PK_USER PRIMARY KEY(USER_ID) 
);

INSERT INTO TBL_USER
(USER_ID, LOGIN_ID, PASSWORD, NAME, GENDER)
VALUES(SEQ_USER.nextval, 'aaa', '1234', 'aaa', 'M');
 
SELECT * FROM TBL_USER tu ;

DROP SEQUENCE SEQ_MEMBER;
DROP TABLE MEMBERS ;

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	MEMBER_ID NUMBER,
	LOGIN_ID VARCHAR2(1000),
	PASSWORD VARCHAR2(1000),
	NAME VARCHAR2(1000),
	AGE NUMBER,
	GENDER CHAR(1),
	CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID) 
);

INSERT INTO TBL_MEMBER(MEMBER_ID, LOGIN_ID, PASSWORD, NAME, AGE, GENDER)
VALUES(0, '', '', '', 0, '')

SELECT * FROM TBL_MEMBER tm ;
